version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: .
    container_name: vinhood
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"
    env_file:
      - ".env"
    depends_on:
      - db